### PR TITLE
Fixes for code not working

### PR DESCRIPTION
**Pull request by ghost**
This example code doesn't work!
```
// Example:
// 
// include_once('ChatGPT.php'); // include class from folder
// $ai = new ChatGPT();         // initialize class object
// echo $ai->generateImage('a cat on a post lamp');               // print the image URL
// echo $ai->createTextRequest('what is the weather in Romania?') // print the text response
```

Added `$this->data = array();` right before return on both functions and it fixed it nicely.
(if you call image it'll pass ` $this->data["n"] && $this->data["size"];` onto the next request, and if it texts it'll error out)

### CODE REVIEW

**Comment by Radulepy** [comment]
HI @dehlirious can I see an example on how did you call the class and did not worked? By adding `$this->data = array();` before a return you are only setting the $this->data object to an empty arrray it has nothing to do with the $response object coming from the API call. Adding an empty array before the return statement `$this->data = array();` to your project could have fixed an underlying issue with your request. 
Please correct me if I'm wrong.

**Comment by ghost** [comment]
> HI @dehlirious can I see an example on how did you call the class and did not worked? By adding `$this->data = array();` before a return you are only setting the $this->data object to an empty arrray it has nothing to do with the $response object coming from the API call. Adding an empty array before the return statement `$this->data = array();` to your project could have fixed an underlying issue with your request. 
> Please correct me if I'm wrong.

The example code I showed above is the exact way I used it, with the chatgpt.php script included, and it gave errors, without having modified anything 

If you use imagegenerate then text generate, $this->data["n"] && $this->data["size"] lingers in $this->data from the image generation and since both functions use $this->data, the n and size params will be passed to the text generation function, if passed, it'll give an error because n and size don't exist for that type of OpenAI query. Thus affecting the response. At least that was my interpretation of the issue, may be wrong, but the solution seems correct.


Emptying the data array at the end of each function fixed the problem, as shown in the commit.
I'm surprised you haven't ran into the issue. As far as I'm aware, there's nothing underlying to cause the issue since no other scripts or code were involved.

**Comment by mriffault** [comment]
He is right, by the way, storing the payload into a $data property is not useful and yes obvisouly may lead to errors when using both of the methods of the same ChatGPT Object successively.
The fix is not really to empty $this->data, which is afterall confusing, but simply remove this property and use a separated $data variable inside each methods.

**Comment by Radulepy** [comment]
> He is right, by the way, storing the payload into a $data property is not useful and yes obvisouly may lead to errors when using both of the methods of the same ChatGPT Object successively. The fix is not really to empty $this->data, which is afterall confusing, but simply remove this property and use a separated $data variable inside each methods.

You are right, I'll modify the data object in the same method. This should have been an starting point only :)
Thanks for the comments!

**Comment by Radulepy** [comment]
@mriffault  @dehlirious 
Thank you for your inputs guys. I refactored and improved the code to be more scalable.

**Pull request closed without merging**
